# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  high_level_summary: false
  poem: false
  review_status: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  in_progress_fortune: false
  auto_review:
    enabled: true
    drafts: false
